env:
  browser: true
  es6: true
extends: airbnb
parser: babel-eslint
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules: {
    "comma-dangle": ["error", "only-multiline"],
    "object-curly-newline": 0,
    "no-plusplus": ["error", {"allowForLoopAfterthoughts": true}],
    "no-restricted-syntax": 0,
    "object-curly-spacing": ["error", "never"],
    "prefer-destructuring": 0,
    "react/forbid-prop-types": 0,
    "react/jsx-filename-extension": [1, {"extensions": [".js", ".jsx"]}]
  }
