const MIN_WIDTH = 200;
const MIN_HEIGHT = 150;

const COLOUR = {
  BLACK: 'BLACK',
  BLUE: 'BLUE',
  PURPLE: 'PURPLE',
  RED: 'RED',
  YELLOW: 'YELLOW',
};

export const palette = {
  [COLOUR.BLACK]: 0x111111,
  [COLOUR.BLUE]: 0x0055CC,
  [COLOUR.PURPLE]: 0xFFCC00,
  [COLOUR.RED]: 0xFF0000,
  [COLOUR.YELLOW]: 0xCCCC00,
};

const GOD = {
  APPOLO: 'APPOLO',
  ARES: 'ARES',
  ATHENA: 'ATHENA',
  POSEIDON: 'POSEIDON',
  ZEUS: 'ZEUS',
};

const TURN_STEP = {
  GATHER_REVENUE: 'GATHER_REVENUE',
  MAKE_OFFERINGS: 'MAKE_OFFERINGS',
  PERFORM_GOD_ACTIONS: 'PERFORM_GOD_ACTIONS',
};

export {
  COLOUR,
  GOD,
  MIN_HEIGHT,
  MIN_WIDTH,
  TURN_STEP,
};
